# Generated by Django 6.0.2 on 2026-03-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in PHP', max_digits=10)),
                ('inclusions', models.TextField(help_text='One inclusion per line. e.g.:\nAdult Pool & Kiddie Pool\nCottages')),
                ('note', models.CharField(blank=True, help_text='Optional note shown below inclusions (e.g. Gas Griller add-on)', max_length=300)),
                ('photo', models.ImageField(blank=True, help_text='Optional banner/header photo for this package', null=True, upload_to='rates/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Rate Package',
                'verbose_name_plural': 'Rate Packages',
                'ordering': ['order', 'name'],
            },
        ),
    ]
