# Generated by Django 6.0.2 on 2026-03-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='map_x',
            field=models.FloatField(default=50.0, help_text='X coordinate on the map (%)'),
        ),
        migrations.AddField(
            model_name='facility',
            name='map_y',
            field=models.FloatField(default=50.0, help_text='Y coordinate on the map (%)'),
        ),
    ]
